"""fase1 base auth y negocio

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 08:24:24.101383
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.15'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate < 1', name=op.f('ck_service_categories_commission_rate_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_service_categories_name'))
    )
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'technician', 'admin', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_users_failed_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('client_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address_line', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_client_profiles'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address_line', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'pending_approval', 'completed', 'disputed', 'cancelled', name='service_request_status'), server_default='open', nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','cancelled') OR technician_id IS NOT NULL", name=op.f('ck_service_requests_technician_required_after_open')),
    sa.CheckConstraint('agreed_price IS NULL OR agreed_price > 0', name=op.f('ck_service_requests_agreed_price_positive')),
    sa.CheckConstraint('technician_id IS NULL OR technician_id <> client_id', name=op.f('ck_service_requests_client_is_not_technician')),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_service_requests_category_id_service_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_service_requests_client_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('fk_service_requests_technician_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests'))
    )
    op.create_index(op.f('ix_service_requests_client_id'), 'service_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_technician_id'), 'service_requests', ['technician_id'], unique=False)
    op.create_table('technician_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='technician_verification_status'), server_default='pending', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('base_city', sa.String(length=80), nullable=True),
    sa.Column('base_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('base_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('coverage_radius_km', sa.SmallInteger(), server_default=sa.text('15'), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payout_account_ref', sa.String(length=120), nullable=True),
    sa.Column('id_document_storage_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coverage_radius_km > 0 AND coverage_radius_km <= 200', name=op.f('ck_technician_profiles_coverage_radius_range')),
    sa.CheckConstraint('jobs_completed >= 0', name=op.f('ck_technician_profiles_jobs_completed_non_negative')),
    sa.CheckConstraint('rating_avg >= 0 AND rating_avg <= 5', name=op.f('ck_technician_profiles_rating_avg_range')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_technician_profiles_rating_count_non_negative')),
    sa.CheckConstraint('years_experience >= 0 AND years_experience <= 70', name=op.f('ck_technician_profiles_years_experience_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_technician_profiles_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_technician_profiles_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_technician_profiles'))
    )
    op.create_index(op.f('ix_technician_profiles_verification_status'), 'technician_profiles', ['verification_status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_request_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('technician_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'MXN'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'held', 'released', 'refunded', 'failed', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_payments_currency_iso4217')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.CheckConstraint('platform_fee + technician_payout = amount', name=op.f('ck_payments_split_matches_amount')),
    sa.CheckConstraint('platform_fee >= 0 AND technician_payout >= 0', name=op.f('ck_payments_split_non_negative')),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], name=op.f('fk_payments_service_request_id_service_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id')),
    sa.UniqueConstraint('service_request_id', name=op.f('uq_payments_service_request_id'))
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_request_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('technician_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_reviews_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], name=op.f('fk_reviews_service_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('fk_reviews_technician_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('service_request_id', name=op.f('uq_reviews_service_request_id'))
    )
    op.create_index(op.f('ix_reviews_technician_id'), 'reviews', ['technician_id'], unique=False)
    op.create_table('technician_services',
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_rate IS NULL OR base_rate >= 0', name=op.f('ck_technician_services_base_rate_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_technician_services_category_id_service_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['technician_profiles.user_id'], name=op.f('fk_technician_services_technician_id_technician_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technician_id', 'category_id', name=op.f('pk_technician_services'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technician_services')
    op.drop_index(op.f('ix_reviews_technician_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_technician_profiles_verification_status'), table_name='technician_profiles')
    op.drop_table('technician_profiles')
    op.drop_index(op.f('ix_service_requests_technician_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_client_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
    # Alembic no elimina los ENUM de PostgreSQL al borrar tablas: se hace explícito.
    for enum_name in ("payment_status", "technician_verification_status",
                      "service_request_status", "user_role"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
