"""KYC de técnicos: expediente, documentos, revisión, auditoría, catálogos y triggers.

Además de las tablas, esta migración:
- siembra catálogos (país, 32 estados INEGI, tipos de documento, motivos de rechazo,
  políticas de retención DESHABILITADAS);
- crea un expediente NOT_STARTED para cada técnico existente (ver nota en _migrate_legacy);
- instala triggers: transiciones válidas del KYC, historial y auditoría solo-inserción,
  domicilios congelados, disponibilidad y asignación de órdenes solo con KYC APPROVED;
- elimina technician_profiles.verification_status y columnas relacionadas.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 08:30:04.583756
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('TECHNICIAN', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('technician_id', sa.Uuid(), nullable=True),
    sa.Column('kyc_profile_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'DENIED', 'ERROR', name='audit_result'), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('reason_note', sa.String(length=1000), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('length(row_hash) = 64', name=op.f('ck_audit_logs_row_hash_len')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_technician', 'audit_logs', ['technician_id', 'occurred_at'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_table('document_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('IDENTITY', 'ADDRESS', 'SELFIE', 'BACKGROUND_CHECK', name='document_category'), nullable=False),
    sa.Column('sides_required', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_files', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('requires_number', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_issue_date', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_expiry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_age_days', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('max_files BETWEEN 1 AND 5', name=op.f('ck_document_types_max_files_range')),
    sa.CheckConstraint('sides_required BETWEEN 1 AND max_files', name=op.f('ck_document_types_sides_within_max')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    sa.UniqueConstraint('code', name=op.f('uq_document_types_code'))
    )
    op.create_table('mx_states',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('curp_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mx_states')),
    sa.UniqueConstraint('curp_code', name=op.f('uq_mx_states_curp_code')),
    sa.UniqueConstraint('name', name=op.f('uq_mx_states_name'))
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_pending', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('rejection_reasons',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.Enum('DOCUMENT', 'CORRECTION', 'REJECTION', 'SUSPENSION', name='reason_scope'), nullable=False),
    sa.Column('requires_note', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rejection_reasons')),
    sa.UniqueConstraint('code', name=op.f('uq_rejection_reasons_code'))
    )
    op.create_table('admin_region_scopes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['mx_states.id'], name=op.f('fk_admin_region_scopes_state_id_mx_states')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_region_scopes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'state_id', name=op.f('pk_admin_region_scopes'))
    )
    op.create_table('admin_role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('KYC_REVIEWER', 'KYC_SUPERVISOR', 'SUPPORT', 'SUPERADMIN', 'FINANCE_VIEWER', 'FINANCE_OPERATOR', 'FINANCE_ADMIN', name='admin_role'), nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_admin_role_assignments_granted_by_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role', name=op.f('pk_admin_role_assignments'))
    )
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notice_version', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('user_id', 'notice_version', 'purpose', name=op.f('uq_consents_user_id'))
    )
    op.create_table('mx_municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.SmallInteger(), nullable=False),
    sa.Column('inegi_code', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['mx_states.id'], name=op.f('fk_mx_municipalities_state_id_mx_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mx_municipalities')),
    sa.UniqueConstraint('state_id', 'inegi_code', name=op.f('uq_mx_municipalities_state_id'))
    )
    op.create_index(op.f('ix_mx_municipalities_state_id'), 'mx_municipalities', ['state_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('data_category', sa.String(length=60), nullable=False),
    sa.Column('trigger_event', sa.String(length=60), nullable=False),
    sa.Column('retain_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('DELETE', 'ANONYMIZE', name='retention_action'), nullable=False),
    sa.Column('legal_basis', sa.String(length=300), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retain_days >= 0', name=op.f('ck_retention_policies_retain_days_non_negative')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_retention_policies_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies')),
    sa.UniqueConstraint('data_category', name=op.f('uq_retention_policies_data_category'))
    )
    op.create_table('kyc_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING_DOCUMENTS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CORRECTION_REQUIRED', 'SUSPENDED', 'EXPIRED', name='kyc_status'), server_default='NOT_STARTED', nullable=False),
    sa.Column('first_names', sa.String(length=80), nullable=True),
    sa.Column('paternal_surname', sa.String(length=80), nullable=True),
    sa.Column('maternal_surname', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('curp_enc', sa.LargeBinary(), nullable=True),
    sa.Column('curp_hash', sa.String(length=64), nullable=True),
    sa.Column('rfc_enc', sa.LargeBinary(), nullable=True),
    sa.Column('rfc_hash', sa.String(length=64), nullable=True),
    sa.Column('data_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('current_address_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cycle', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revalidation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_background_check_badge', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'UNDER_REVIEW') = (assigned_reviewer_id IS NOT NULL)", name=op.f('ck_kyc_profiles_reviewer_only_under_review')),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'PENDING_DOCUMENTS') OR anonymized_at IS NOT NULL OR (first_names IS NOT NULL AND paternal_surname IS NOT NULL AND birth_date IS NOT NULL AND curp_hash IS NOT NULL AND rfc_hash IS NOT NULL AND current_address_id IS NOT NULL)", name=op.f('ck_kyc_profiles_complete_data_after_submission')),
    sa.CheckConstraint("submitted_at IS NULL OR birth_date IS NULL OR birth_date <= (timezone('UTC', submitted_at) - interval '18 years')::date", name=op.f('ck_kyc_profiles_adult_at_submission')),
    sa.CheckConstraint('(curp_enc IS NULL) = (curp_hash IS NULL)', name=op.f('ck_kyc_profiles_curp_enc_and_hash_together')),
    sa.CheckConstraint('(rfc_enc IS NULL) = (rfc_hash IS NULL)', name=op.f('ck_kyc_profiles_rfc_enc_and_hash_together')),
    sa.CheckConstraint('curp_hash IS NULL OR length(curp_hash) = 64', name=op.f('ck_kyc_profiles_curp_hash_len')),
    sa.CheckConstraint('cycle >= 0', name=op.f('ck_kyc_profiles_cycle_non_negative')),
    sa.CheckConstraint('rfc_hash IS NULL OR length(rfc_hash) = 64', name=op.f('ck_kyc_profiles_rfc_hash_len')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_kyc_profiles_approved_by_id_users')),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], name=op.f('fk_kyc_profiles_assigned_reviewer_id_users')),
    sa.ForeignKeyConstraint(['technician_id'], ['technician_profiles.user_id'], name=op.f('fk_kyc_profiles_technician_id_technician_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_profiles')),
    sa.UniqueConstraint('curp_hash', name=op.f('uq_kyc_profiles_curp_hash')),
    sa.UniqueConstraint('rfc_hash', name=op.f('uq_kyc_profiles_rfc_hash')),
    sa.UniqueConstraint('technician_id', name=op.f('uq_kyc_profiles_technician_id'))
    )
    op.create_index('ix_kyc_profiles_expires_at', 'kyc_profiles', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'APPROVED'"))
    op.create_index('ix_kyc_profiles_queue', 'kyc_profiles', ['status', 'submitted_at'], unique=False)
    op.create_table('mx_postal_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('settlement_type', sa.String(length=60), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('sepomex_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("postal_code ~ '^[0-9]{5}$'", name=op.f('ck_mx_postal_settlements_postal_code_format')),
    sa.ForeignKeyConstraint(['municipality_id'], ['mx_municipalities.id'], name=op.f('fk_mx_postal_settlements_municipality_id_mx_municipalities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mx_postal_settlements')),
    sa.UniqueConstraint('postal_code', 'municipality_id', 'sepomex_id', name=op.f('uq_mx_postal_settlements_postal_code'))
    )
    op.create_index(op.f('ix_mx_postal_settlements_postal_code'), 'mx_postal_settlements', ['postal_code'], unique=False)
    op.create_table('kyc_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kyc_profile_id', sa.Uuid(), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('exterior_number', sa.String(length=20), nullable=False),
    sa.Column('interior_number', sa.String(length=20), nullable=True),
    sa.Column('settlement', sa.String(length=150), nullable=False),
    sa.Column('postal_settlement_id', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.SmallInteger(), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default=sa.text("'MX'"), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("postal_code ~ '^[0-9]{5}$'", name=op.f('ck_kyc_addresses_postal_code_format')),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_kyc_addresses_country_code_countries')),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], name=op.f('fk_kyc_addresses_kyc_profile_id_kyc_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['mx_municipalities.id'], name=op.f('fk_kyc_addresses_municipality_id_mx_municipalities')),
    sa.ForeignKeyConstraint(['postal_settlement_id'], ['mx_postal_settlements.id'], name=op.f('fk_kyc_addresses_postal_settlement_id_mx_postal_settlements')),
    sa.ForeignKeyConstraint(['state_id'], ['mx_states.id'], name=op.f('fk_kyc_addresses_state_id_mx_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_addresses'))
    )
    op.create_index(op.f('ix_kyc_addresses_kyc_profile_id'), 'kyc_addresses', ['kyc_profile_id'], unique=False)
    op.create_table('kyc_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kyc_profile_id', sa.Uuid(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'CORRECTION_REQUIRED', 'REJECTED', name='review_decision'), nullable=True),
    sa.Column('reason_id', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('address_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], name=op.f('fk_kyc_reviews_kyc_profile_id_kyc_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['rejection_reasons.id'], name=op.f('fk_kyc_reviews_reason_id_rejection_reasons')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_kyc_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_reviews')),
    sa.UniqueConstraint('kyc_profile_id', 'cycle', name=op.f('uq_kyc_reviews_kyc_profile_id'))
    )
    op.create_table('kyc_status_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('kyc_profile_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('NOT_STARTED', 'PENDING_DOCUMENTS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CORRECTION_REQUIRED', 'SUSPENDED', 'EXPIRED', name='kyc_status'), nullable=True),
    sa.Column('to_status', sa.Enum('NOT_STARTED', 'PENDING_DOCUMENTS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CORRECTION_REQUIRED', 'SUSPENDED', 'EXPIRED', name='kyc_status'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('TECHNICIAN', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_kyc_status_history_actor_id_users')),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], name=op.f('fk_kyc_status_history_kyc_profile_id_kyc_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_status_history'))
    )
    op.create_index(op.f('ix_kyc_status_history_kyc_profile_id'), 'kyc_status_history', ['kyc_profile_id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kyc_profile_id', sa.Uuid(), nullable=False),
    sa.Column('document_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'SCANNING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'INVALID', 'SUPERSEDED', 'EXPIRED', name='kyc_document_status'), server_default='UPLOADING', nullable=False),
    sa.Column('number_enc', sa.LargeBinary(), nullable=True),
    sa.Column('number_hash', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('review_cycle', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason_id', sa.SmallInteger(), nullable=True),
    sa.Column('rejection_note', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(number_enc IS NULL) = (number_hash IS NULL)', name=op.f('ck_kyc_documents_number_enc_and_hash_together')),
    sa.CheckConstraint('expires_at IS NULL OR issued_at IS NULL OR expires_at > issued_at', name=op.f('ck_kyc_documents_expiry_after_issue')),
    sa.CheckConstraint('supersedes_id IS NULL OR supersedes_id <> id', name=op.f('ck_kyc_documents_not_self_superseding')),
    sa.ForeignKeyConstraint(['address_id'], ['kyc_addresses.id'], name=op.f('fk_kyc_documents_address_id_kyc_addresses')),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_kyc_documents_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], name=op.f('fk_kyc_documents_kyc_profile_id_kyc_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejection_reason_id'], ['rejection_reasons.id'], name=op.f('fk_kyc_documents_rejection_reason_id_rejection_reasons')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_kyc_documents_reviewed_by_id_users')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['kyc_documents.id'], name=op.f('fk_kyc_documents_supersedes_id_kyc_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_documents'))
    )
    op.create_index('ix_kyc_documents_expiring', 'kyc_documents', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'APPROVED'"))
    op.create_index(op.f('ix_kyc_documents_kyc_profile_id'), 'kyc_documents', ['kyc_profile_id'], unique=False)
    op.create_index('ix_kyc_documents_number_hash', 'kyc_documents', ['number_hash'], unique=False)
    op.create_table('kyc_document_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('FRONT', 'BACK', 'PAGE', 'SELFIE', name='document_side'), nullable=False),
    sa.Column('page_number', sa.SmallInteger(), nullable=True),
    sa.Column('bucket', sa.String(length=63), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('detected_mime', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'INVALID', 'ERROR', name='scan_status'), server_default='PENDING', nullable=False),
    sa.Column('scan_engine', sa.String(length=60), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preview_key', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("detected_mime IN ('image/jpeg', 'image/png', 'application/pdf')", name=op.f('ck_kyc_document_files_mime_allowed')),
    sa.CheckConstraint("object_key !~ '[^a-z0-9/_-]'", name=op.f('ck_kyc_document_files_object_key_safe_chars')),
    sa.CheckConstraint('length(sha256) = 64', name=op.f('ck_kyc_document_files_sha256_len')),
    sa.CheckConstraint('size_bytes > 0 AND size_bytes <= 10485760', name=op.f('ck_kyc_document_files_size_range')),
    sa.ForeignKeyConstraint(['document_id'], ['kyc_documents.id'], name=op.f('fk_kyc_document_files_document_id_kyc_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_document_files')),
    sa.UniqueConstraint('object_key', name=op.f('uq_kyc_document_files_object_key'))
    )
    op.create_index(op.f('ix_kyc_document_files_document_id'), 'kyc_document_files', ['document_id'], unique=False)
    op.create_index('ix_kyc_document_files_sha256', 'kyc_document_files', ['sha256'], unique=False)
    op.create_table('kyc_document_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='document_decision'), nullable=False),
    sa.Column('reason_id', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision = 'APPROVED' OR reason_id IS NOT NULL", name=op.f('ck_kyc_document_reviews_rejection_needs_reason')),
    sa.ForeignKeyConstraint(['document_id'], ['kyc_documents.id'], name=op.f('fk_kyc_document_reviews_document_id_kyc_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['rejection_reasons.id'], name=op.f('fk_kyc_document_reviews_reason_id_rejection_reasons')),
    sa.ForeignKeyConstraint(['review_id'], ['kyc_reviews.id'], name=op.f('fk_kyc_document_reviews_review_id_kyc_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_kyc_document_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_document_reviews')),
    sa.UniqueConstraint('review_id', 'document_id', name=op.f('uq_kyc_document_reviews_review_id'))
    )
    # Llave circular kyc_profiles -> kyc_addresses (autogenerate la omite con use_alter).
    op.create_foreign_key('fk_kyc_profiles_current_address_id_kyc_addresses', 'kyc_profiles',
                          'kyc_addresses', ['current_address_id'], ['id'])

    _seed_catalogs()
    _migrate_legacy()
    for sql in TRIGGERS_UP:
        op.execute(sql)

    op.drop_index(op.f('ix_technician_profiles_verification_status'), table_name='technician_profiles')
    op.drop_constraint(op.f('fk_technician_profiles_verified_by_id_users'), 'technician_profiles', type_='foreignkey')
    op.drop_column('technician_profiles', 'id_document_storage_key')
    op.drop_column('technician_profiles', 'verified_at')
    op.drop_column('technician_profiles', 'verified_by_id')
    op.drop_column('technician_profiles', 'verification_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    for sql in TRIGGERS_DOWN:
        op.execute(sql)
    op.drop_constraint('fk_kyc_profiles_current_address_id_kyc_addresses', 'kyc_profiles', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technician_profiles', sa.Column('verification_status', postgresql.ENUM('pending', 'approved', 'rejected', 'suspended', name='technician_verification_status'), server_default=sa.text("'pending'::technician_verification_status"), autoincrement=False, nullable=False))
    op.add_column('technician_profiles', sa.Column('verified_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('technician_profiles', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('technician_profiles', sa.Column('id_document_storage_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_technician_profiles_verified_by_id_users'), 'technician_profiles', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_technician_profiles_verification_status'), 'technician_profiles', ['verification_status'], unique=False)
    op.drop_table('kyc_document_reviews')
    op.drop_index('ix_kyc_document_files_sha256', table_name='kyc_document_files')
    op.drop_index(op.f('ix_kyc_document_files_document_id'), table_name='kyc_document_files')
    op.drop_table('kyc_document_files')
    op.drop_index('ix_kyc_documents_number_hash', table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_kyc_profile_id'), table_name='kyc_documents')
    op.drop_index('ix_kyc_documents_expiring', table_name='kyc_documents', postgresql_where=sa.text("status = 'APPROVED'"))
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_kyc_status_history_kyc_profile_id'), table_name='kyc_status_history')
    op.drop_table('kyc_status_history')
    op.drop_table('kyc_reviews')
    op.drop_index(op.f('ix_kyc_addresses_kyc_profile_id'), table_name='kyc_addresses')
    op.drop_table('kyc_addresses')
    op.drop_index(op.f('ix_mx_postal_settlements_postal_code'), table_name='mx_postal_settlements')
    op.drop_table('mx_postal_settlements')
    op.drop_index('ix_kyc_profiles_queue', table_name='kyc_profiles')
    op.drop_index('ix_kyc_profiles_expires_at', table_name='kyc_profiles', postgresql_where=sa.text("status = 'APPROVED'"))
    op.drop_table('kyc_profiles')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_mx_municipalities_state_id'), table_name='mx_municipalities')
    op.drop_table('mx_municipalities')
    op.drop_table('consents')
    op.drop_table('admin_role_assignments')
    op.drop_table('admin_region_scopes')
    op.drop_table('rejection_reasons')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('outbox_events')
    op.drop_table('mx_states')
    op.drop_table('document_types')
    op.drop_table('countries')
    op.drop_index('ix_audit_logs_technician', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
    for enum_name in ("kyc_document_status", "document_category", "document_side", "scan_status",
                      "review_decision", "document_decision", "reason_scope", "audit_result",
                      "admin_role", "retention_action", "kyc_status", "actor_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)


# =============================================================================
# Semillas
# =============================================================================
MX_STATES = [  # (clave INEGI, clave CURP, nombre)
    (1, "AS", "Aguascalientes"), (2, "BC", "Baja California"), (3, "BS", "Baja California Sur"),
    (4, "CC", "Campeche"), (5, "CL", "Coahuila de Zaragoza"), (6, "CM", "Colima"), (7, "CS", "Chiapas"),
    (8, "CH", "Chihuahua"), (9, "DF", "Ciudad de México"), (10, "DG", "Durango"), (11, "GT", "Guanajuato"),
    (12, "GR", "Guerrero"), (13, "HG", "Hidalgo"), (14, "JC", "Jalisco"), (15, "MC", "México"),
    (16, "MN", "Michoacán de Ocampo"), (17, "MS", "Morelos"), (18, "NT", "Nayarit"), (19, "NL", "Nuevo León"),
    (20, "OC", "Oaxaca"), (21, "PL", "Puebla"), (22, "QT", "Querétaro"), (23, "QR", "Quintana Roo"),
    (24, "SP", "San Luis Potosí"), (25, "SL", "Sinaloa"), (26, "SR", "Sonora"), (27, "TC", "Tabasco"),
    (28, "TS", "Tamaulipas"), (29, "TL", "Tlaxcala"), (30, "VZ", "Veracruz de Ignacio de la Llave"),
    (31, "YN", "Yucatán"), (32, "ZS", "Zacatecas"),
]

# id, code, name, category, sides_required, max_files, number, issue, expiry, max_age_days, active, order
DOCUMENT_TYPES = [
    (1, "INE", "Credencial para votar (INE)", "IDENTITY", 2, 2, True, False, True, None, True, 10),
    (2, "PASSPORT_MX", "Pasaporte mexicano", "IDENTITY", 1, 1, True, False, True, None, True, 20),
    # Inactivo hasta confirmar su estatus legal como identificación (ver doc Fase 0, D1).
    (3, "CURP_BIOMETRIC", "CURP biométrica", "IDENTITY", 2, 2, True, False, False, None, False, 30),
    (4, "OTHER_OFFICIAL_ID", "Otra identificación oficial autorizada", "IDENTITY", 1, 2, True, False, True, None, False, 40),
    (10, "UTILITY_ELECTRICITY", "Recibo de luz", "ADDRESS", 1, 3, False, True, False, 90, True, 50),
    (11, "UTILITY_WATER", "Recibo de agua", "ADDRESS", 1, 3, False, True, False, 90, True, 51),
    (12, "UTILITY_INTERNET", "Recibo de internet", "ADDRESS", 1, 3, False, True, False, 90, True, 52),
    (13, "UTILITY_PHONE", "Recibo de teléfono", "ADDRESS", 1, 3, False, True, False, 90, True, 53),
    (14, "OFFICIAL_ADDRESS_CERT", "Constancia de domicilio oficial", "ADDRESS", 1, 3, False, True, False, 90, True, 54),
    (20, "SELFIE_WITH_ID", "Selfie sosteniendo tu identificación", "SELFIE", 1, 1, False, False, False, None, True, 60),
    (30, "CRIMINAL_RECORD_CERT", "Carta de antecedentes no penales", "BACKGROUND_CHECK", 1, 3, False, True, False, 90, True, 70),
]

# id, code, label, scope, requires_note
REJECTION_REASONS = [
    (1, "DOCUMENTO_ILEGIBLE", "Documento ilegible", "DOCUMENT", False),
    (2, "DOCUMENTO_VENCIDO", "Documento vencido", "DOCUMENT", False),
    (3, "DATOS_NO_COINCIDEN", "Los datos no coinciden", "DOCUMENT", False),
    (4, "DOCUMENTO_INCOMPLETO", "Documento incompleto", "DOCUMENT", False),
    (5, "DOMICILIO_NO_COINCIDE", "El domicilio no coincide", "DOCUMENT", False),
    (6, "DOCUMENTO_NO_VALIDO", "Documento no válido", "DOCUMENT", False),
    (7, "SELFIE_NO_COINCIDE", "La selfie no coincide con la identificación", "DOCUMENT", False),
    (8, "OTRO", "Otro motivo", "DOCUMENT", True),
    (20, "CORRECCION_DATOS_PERSONALES", "Corregir datos personales", "CORRECTION", True),
    (21, "CORRECCION_DOCUMENTOS", "Corregir documentos marcados", "CORRECTION", False),
    (40, "FRAUDE_IDENTIDAD", "Suplantación o fraude de identidad", "REJECTION", True),
    (41, "MENOR_DE_EDAD", "Menor de edad", "REJECTION", False),
    (42, "DOCUMENTO_FALSO", "Documento falso o alterado", "REJECTION", True),
    (43, "CUENTA_DUPLICADA", "Cuenta duplicada", "REJECTION", True),
    (60, "QUEJAS_REITERADAS", "Quejas reiteradas de clientes", "SUSPENSION", True),
    (61, "INVESTIGACION_EN_CURSO", "Investigación en curso", "SUSPENSION", True),
    (62, "INCUMPLIMIENTO_TERMINOS", "Incumplimiento de términos", "SUSPENSION", True),
    (63, "DOCUMENTO_OBLIGATORIO_VENCIDO", "Documento obligatorio vencido", "SUSPENSION", False),
]

# Propuestas de la Fase 0. TODAS deshabilitadas hasta validación legal.
RETENTION_POLICIES = [
    (1, "QUARANTINE_FILES", "file_uploaded", 1, "DELETE", "Archivos en cuarentena, infectados o inválidos"),
    (2, "DISCARDED_DOCUMENTS", "document_discarded", 30, "DELETE", "Documentos descartados antes de enviar"),
    (3, "SUPERSEDED_DOCUMENTS", "document_superseded", 365, "DELETE", "Documentos reemplazados; se conserva el metadato"),
    (4, "REJECTED_PROFILES", "kyc_rejected", 365, "ANONYMIZE", "Defensa ante fraude y reclamaciones; por validar con abogado"),
    (5, "CLOSED_ACCOUNTS", "account_closed", 1825, "ANONYMIZE", "Obligaciones fiscales (plazo general CFF); por validar con contador"),
    (6, "AUDIT_NETWORK_DATA", "audit_written", 365, "ANONYMIZE", "IP y user-agent de auditoría"),
]


def _seed_catalogs() -> None:
    op.bulk_insert(sa.table("countries", sa.column("code"), sa.column("name")), [{"code": "MX", "name": "México"}])
    op.bulk_insert(
        sa.table("mx_states", sa.column("id", sa.SmallInteger), sa.column("curp_code"), sa.column("name")),
        [{"id": i, "curp_code": c, "name": n} for i, c, n in MX_STATES],
    )
    dt = sa.table("document_types", *(sa.column(c) for c in (
        "id", "code", "name", "category", "sides_required", "max_files", "requires_number",
        "requires_issue_date", "requires_expiry", "max_age_days", "is_active", "sort_order")))
    op.bulk_insert(dt, [dict(zip(("id", "code", "name", "category", "sides_required", "max_files",
                                  "requires_number", "requires_issue_date", "requires_expiry",
                                  "max_age_days", "is_active", "sort_order"), row)) for row in DOCUMENT_TYPES])
    rr = sa.table("rejection_reasons", sa.column("id"), sa.column("code"), sa.column("label"),
                  sa.column("scope"), sa.column("requires_note"))
    op.bulk_insert(rr, [dict(zip(("id", "code", "label", "scope", "requires_note"), r)) for r in REJECTION_REASONS])
    rp = sa.table("retention_policies", sa.column("id"), sa.column("data_category"), sa.column("trigger_event"),
                  sa.column("retain_days"), sa.column("action"), sa.column("legal_basis"), sa.column("is_enabled"))
    op.bulk_insert(rp, [dict(zip(("id", "data_category", "trigger_event", "retain_days", "action", "legal_basis"), r),
                             is_enabled=False) for r in RETENTION_POLICIES])


def _migrate_legacy() -> None:
    """
    Crea un expediente para cada técnico existente.

    DECISIÓN: todos quedan en NOT_STARTED, incluidos los que tenían verification_status
    = 'approved'. Esa aprobación era un simple cambio de campo sin documentos, así que no
    equivale a un KYC. Deben completar la verificación antes de volver a recibir órdenes.
    """
    import uuid

    from app.core.crypto import new_wrapped_dek  # requiere KYC_MASTER_KEY configurada

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT user_id, verification_status::text FROM technician_profiles")).all()
    for user_id, legacy in rows:
        pid = uuid.uuid4()
        bind.execute(sa.text(
            "INSERT INTO kyc_profiles (id, technician_id, status, data_key_enc) "
            "VALUES (:id, :tid, 'NOT_STARTED', :dek)"
        ), {"id": pid, "tid": user_id, "dek": new_wrapped_dek(pid)})
        bind.execute(sa.text(
            "INSERT INTO kyc_status_history (kyc_profile_id, from_status, to_status, actor_type, note) "
            "VALUES (:id, NULL, 'NOT_STARTED', 'SYSTEM', :note)"
        ), {"id": pid, "note": f"Migración 0002: verification_status anterior = {legacy}"})
    bind.execute(sa.text("UPDATE technician_profiles SET is_available = false"))


# =============================================================================
# Triggers
# =============================================================================
# Debe coincidir EXACTAMENTE con app.kyc.state_machine.ALLOWED_TRANSITIONS
# (tests/test_kyc_db.py lo verifica).
_ALLOWED = [
    "NOT_STARTED>PENDING_DOCUMENTS", "PENDING_DOCUMENTS>SUBMITTED", "SUBMITTED>UNDER_REVIEW",
    "UNDER_REVIEW>SUBMITTED", "UNDER_REVIEW>APPROVED", "UNDER_REVIEW>CORRECTION_REQUIRED",
    "UNDER_REVIEW>REJECTED", "CORRECTION_REQUIRED>SUBMITTED", "APPROVED>SUSPENDED",
    "APPROVED>EXPIRED", "EXPIRED>SUBMITTED", "SUSPENDED>UNDER_REVIEW",
]
_ALLOWED_SQL = ", ".join(f"'{t}'" for t in _ALLOWED)

TRIGGERS_UP = [
    # 1. Transiciones del KYC
    f"""
    CREATE FUNCTION kyc_enforce_transition() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            IF NEW.status <> 'NOT_STARTED' THEN
                RAISE EXCEPTION 'KYC_INVALID_INITIAL_STATUS: %', NEW.status USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END IF;
        IF NEW.status IS DISTINCT FROM OLD.status
           AND NOT ((OLD.status::text || '>' || NEW.status::text) = ANY (ARRAY[{_ALLOWED_SQL}])) THEN
            RAISE EXCEPTION 'KYC_INVALID_TRANSITION: % -> %', OLD.status, NEW.status
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END $$;
    """,
    """
    CREATE TRIGGER trg_kyc_profiles_transition
        BEFORE INSERT OR UPDATE OF status ON kyc_profiles
        FOR EACH ROW EXECUTE FUNCTION kyc_enforce_transition();
    """,
    # 2. Historial y auditoría: solo inserción
    """
    CREATE FUNCTION forbid_update_delete() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION 'APPEND_ONLY: % no admite %', TG_TABLE_NAME, TG_OP USING ERRCODE = 'insufficient_privilege';
    END $$;
    """,
    """
    CREATE TRIGGER trg_audit_logs_append_only BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
    """,
    """
    CREATE TRIGGER trg_kyc_status_history_append_only BEFORE UPDATE OR DELETE ON kyc_status_history
        FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
    """,
    # 3. Domicilios congelados al enviarse a revisión
    """
    CREATE FUNCTION kyc_address_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.locked_at IS NOT NULL THEN
            RAISE EXCEPTION 'KYC_ADDRESS_LOCKED: el domicilio % ya fue enviado a revisión', OLD.id
                USING ERRCODE = 'check_violation';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$;
    """,
    """
    CREATE TRIGGER trg_kyc_addresses_immutable BEFORE UPDATE OR DELETE ON kyc_addresses
        FOR EACH ROW EXECUTE FUNCTION kyc_address_immutable();
    """,
    # 4. Disponibilidad solo con KYC aprobado
    """
    CREATE FUNCTION technician_availability_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.is_available AND NOT EXISTS (
            SELECT 1 FROM kyc_profiles k WHERE k.technician_id = NEW.user_id AND k.status = 'APPROVED'
        ) THEN
            RAISE EXCEPTION 'KYC_NOT_APPROVED: el técnico no puede marcarse disponible'
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END $$;
    """,
    """
    CREATE TRIGGER trg_technician_availability BEFORE INSERT OR UPDATE OF is_available ON technician_profiles
        FOR EACH ROW EXECUTE FUNCTION technician_availability_guard();
    """,
    # 5. Al salir de APPROVED, el técnico deja de estar disponible
    """
    CREATE FUNCTION kyc_unavailable_when_not_approved() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.status = 'APPROVED' AND NEW.status <> 'APPROVED' THEN
            UPDATE technician_profiles SET is_available = false WHERE user_id = NEW.technician_id;
        END IF;
        RETURN NEW;
    END $$;
    """,
    """
    CREATE TRIGGER trg_kyc_profiles_unavailable AFTER UPDATE OF status ON kyc_profiles
        FOR EACH ROW EXECUTE FUNCTION kyc_unavailable_when_not_approved();
    """,
    # 6. Regla crítica: asignar una orden exige KYC APPROVED y usuario activo
    """
    CREATE FUNCTION service_request_assignment_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.technician_id IS NOT NULL
           AND (TG_OP = 'INSERT' OR NEW.technician_id IS DISTINCT FROM OLD.technician_id) THEN
            PERFORM 1 FROM kyc_profiles k JOIN users u ON u.id = k.technician_id
             WHERE k.technician_id = NEW.technician_id AND k.status = 'APPROVED' AND u.is_active
             FOR SHARE OF k;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'KYC_NOT_APPROVED: el técnico no puede recibir órdenes'
                    USING ERRCODE = 'check_violation';
            END IF;
        END IF;
        RETURN NEW;
    END $$;
    """,
    """
    CREATE TRIGGER trg_service_requests_assignment BEFORE INSERT OR UPDATE OF technician_id ON service_requests
        FOR EACH ROW EXECUTE FUNCTION service_request_assignment_guard();
    """,
]

TRIGGERS_DOWN = [
    "DROP TRIGGER IF EXISTS trg_service_requests_assignment ON service_requests",
    "DROP FUNCTION IF EXISTS service_request_assignment_guard()",
    "DROP TRIGGER IF EXISTS trg_kyc_profiles_unavailable ON kyc_profiles",
    "DROP FUNCTION IF EXISTS kyc_unavailable_when_not_approved()",
    "DROP TRIGGER IF EXISTS trg_technician_availability ON technician_profiles",
    "DROP FUNCTION IF EXISTS technician_availability_guard()",
    "DROP TRIGGER IF EXISTS trg_kyc_addresses_immutable ON kyc_addresses",
    "DROP FUNCTION IF EXISTS kyc_address_immutable()",
    "DROP TRIGGER IF EXISTS trg_kyc_status_history_append_only ON kyc_status_history",
    "DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs",
    "DROP FUNCTION IF EXISTS forbid_update_delete()",
    "DROP TRIGGER IF EXISTS trg_kyc_profiles_transition ON kyc_profiles",
    "DROP FUNCTION IF EXISTS kyc_enforce_transition()",
]
