"""Protección de datos y documentos KYC.

- encryption_keys_metadata: metadatos (nunca material) de las llaves; se registran como
  ACTIVE las llaves configuradas al migrar, con su huella.
- kyc_document_files: llave por archivo (file_key_enc), intentos y detalle de escaneo.
- kyc_documents.risk_flags, file_view_tickets e índice de auditoría por actor.

Nota: autogenerate no detecta CHECK nuevos en tablas existentes; se agregan a mano.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23 09:19:20.888462
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_keys_metadata',
    sa.Column('purpose', sa.Enum('KYC_KEK', 'BLIND_INDEX', name='key_purpose'), nullable=False),
    sa.Column('key_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DECRYPT_ONLY', 'REVOKED', name='key_status'), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.CheckConstraint("status <> 'REVOKED' OR revoked_at IS NOT NULL", name=op.f('ck_encryption_keys_metadata_revoked_has_date')),
    sa.CheckConstraint('key_id BETWEEN 1 AND 255', name=op.f('ck_encryption_keys_metadata_key_id_range')),
    sa.PrimaryKeyConstraint('purpose', 'key_id', name=op.f('pk_encryption_keys_metadata'))
    )
    op.create_index('uq_encryption_keys_one_active', 'encryption_keys_metadata', ['purpose'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('file_view_tickets',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['kyc_document_files.id'], name=op.f('fk_file_view_tickets_file_id_kyc_document_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_file_view_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_file_view_tickets'))
    )
    op.create_index('ix_audit_logs_actor_action', 'audit_logs', ['actor_id', 'action', 'occurred_at'], unique=False)
    op.add_column('kyc_document_files', sa.Column('file_key_enc', sa.LargeBinary(), nullable=True))
    op.add_column('kyc_document_files', sa.Column('scan_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('kyc_document_files', sa.Column('scan_detail', sa.String(length=200), nullable=True))
    op.create_index('ix_kyc_document_files_pending', 'kyc_document_files', ['created_at'], unique=False, postgresql_where=sa.text("scan_status = 'PENDING'"))
    op.add_column('kyc_documents', sa.Column('risk_flags', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    # Si hubiera archivos sin llave (no debería: la subida no existía antes de esta versión),
    # la restricción falla y la migración se detiene en lugar de dejar archivos sin cifrar.
    op.create_check_constraint("key_or_purged", "kyc_document_files",
                               "file_key_enc IS NOT NULL OR purged_at IS NOT NULL")
    op.create_check_constraint("scan_attempts_non_negative", "kyc_document_files", "scan_attempts >= 0")
    _register_configured_keys()


def _register_configured_keys() -> None:
    from app.core.config import get_settings
    from app.core.crypto import _b64_key, key_fingerprint

    s = get_settings()
    rows = [
        ("KYC_KEK", s.KYC_MASTER_KEY_ID,
         key_fingerprint(_b64_key(s.KYC_MASTER_KEY.get_secret_value(), "KYC_MASTER_KEY"))),
        ("BLIND_INDEX", 1,
         key_fingerprint(_b64_key(s.KYC_BLIND_INDEX_KEY.get_secret_value(), "KYC_BLIND_INDEX_KEY"))),
    ]
    for purpose, key_id, fp in rows:
        op.execute(sa.text(
            "INSERT INTO encryption_keys_metadata (purpose, key_id, status, provider, fingerprint, activated_at, notes) "
            "VALUES (CAST(:p AS key_purpose), :k, 'ACTIVE', 'local', :fp, now(), 'Registrada por la migración 0004')"
        ).bindparams(p=purpose, k=key_id, fp=fp))


def downgrade() -> None:
    op.drop_constraint("scan_attempts_non_negative", "kyc_document_files", type_="check")
    op.drop_constraint("key_or_purged", "kyc_document_files", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_documents', 'risk_flags')
    op.drop_index('ix_kyc_document_files_pending', table_name='kyc_document_files', postgresql_where=sa.text("scan_status = 'PENDING'"))
    op.drop_column('kyc_document_files', 'scan_detail')
    op.drop_column('kyc_document_files', 'scan_attempts')
    op.drop_column('kyc_document_files', 'file_key_enc')
    op.drop_index('ix_audit_logs_actor_action', table_name='audit_logs')
    op.drop_table('file_view_tickets')
    op.drop_index('uq_encryption_keys_one_active', table_name='encryption_keys_metadata', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('encryption_keys_metadata')
    # ### end Alembic commands ###
    for enum_name in ("key_status", "key_purpose"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
